In [1]:
import pickle
import pandas as pd
import deepchem as dc
import torch
from torch_geometric.data import Data
from sklearn.model_selection import train_test_split

C:\Users\noton\miniconda3\envs\OPSdesign2\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\noton\miniconda3\envs\OPSdesign2\Lib\site-packages\deepchem\feat\smiles_tokenizer.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

WARNING:tensorflow:From C:\Users\noton\miniconda3\envs\OPSdesign2\Lib\site-packages\tensorflow\python\util\deprecation.py:588: calling function (from tensorflow.python.eager.polymorphic_function.polymorphic_function) with experimental_relax_shapes is deprecated and will be removed in a future version.
Instructions for updating:
experimental_relax_shapes is deprecated, use reduce_retracing instead

In [2]:
torch.manual_seed(42)
df = pd.read_csv('data/data_B3LYP.csv')
df

,SMILES,eHOMO,eLUMO,DE_S0S1,f_S0S1,DE_S0T1,DES1T1
0,CN(C)c1ccc(-c2ccon2)cc1,-5.3318,-0.8751,4.0886,0.4406,2.9556,1.1330
1,CN(C)c1ccc(-c2ccno2)cc1,-5.3511,-1.0814,3.9626,0.8254,2.7849,1.1777
2,CN(C)c1ccc(-c2cnoc2)cc1,-5.2600,-0.6955,4.1000,0.1523,3.0855,1.0145
3,CN(C)c1ccc(-c2ncco2)cc1,-5.2670,-0.9026,4.0425,0.8740,2.8385,1.2040
4,CN(C)c1ccc(-c2cocn2)cc1,-5.1479,-0.5965,4.1345,0.2043,2.9304,1.2041
...,...,...,...,...,...,...,...
54259,COc1cc(OCc2cc(-n3c4ccc(C)cc4c4cc(C)ccc43)cs2)c...,-5.5239,-1.8153,3.4937,0.2572,2.8945,0.5992
54260,c1cnc2c(c1)-c1ccc(-c3ccc4sc5ccccc5c4c3)cc1[SiH2]2,-5.9038,-1.6994,3.7451,0.6591,2.8028,0.9423
54261,C=Cc1cccn1Cn1c2ccc(F)cc2c2cc(F)ccc21,-5.7193,-1.4384,3.7226,0.0379,2.9092,0.8134
54262,N#CC(C#N)=C1C(=Cc2ccc(-c3cccc(S(=O)(=O)Cn4c5cc...,-5.9626,-3.3873,2.3419,0.0005,2.0087,0.3332
54263,Clc1ccc2c(c1)c1cc(Cl)cc(-c3c4ncsc4cc4ncsc34)c1...,-5.7359,-1.8501,3.3485,0.1353,2.6309,0.7176

In [3]:
torch.manual_seed(42)
df_real = pd.read_csv('data/100OPS_B3LYP_with_canon.csv')
df_real_d = df_real.drop(['mol_ID'], axis=1)
df_real_d

,SMILES,eHOMO,eLUMO,DE_S0S1,f_S0S1,DE_S0T1,DES1T1
0,Cc1cc(C)c(-c2c3ccc(C(C)(C)C)cc3[n+](-c3ccccc3)...,-7.0989,-3.7527,2.5966,0.0000,1.9501,0.6465
1,N#Cc1c(N(c2ccc(F)cc2)c2ccc(F)cc2)c(C#N)c(N(c2c...,-5.5345,-2.4904,2.4077,0.0619,2.1712,0.2365
2,N#Cc1c(N(c2ccc(Cl)cc2)c2ccc(Cl)cc2)c(C#N)c(N(c...,-5.6303,-2.5881,2.4331,0.0715,2.1710,0.2621
3,N#Cc1c(N(c2ccc(Br)cc2)c2ccc(Br)cc2)c(C#N)c(N(c...,-5.6711,-2.5968,2.4312,0.0297,2.2978,0.1334
4,N#Cc1c(-n2c3ccccc3c3ccccc32)c(Cl)c(-n2c3ccccc3...,-6.0725,-2.8855,2.5343,0.0339,2.3935,0.1408
...,...,...,...,...,...,...,...
95,COc1ccc(-c2cc(-c3ccc(OC)cc3)[o+]c(-c3ccc(OC)cc...,-6.6505,-3.5299,2.6761,0.5841,2.1605,0.5156
96,C[n+]1c2ccccc2cc2ccccc21,-7.4279,-3.9307,3.0142,0.0670,1.9792,1.0350
97,C[n+]1c2ccccc2c(-c2ccccc2)c2ccccc21,-7.3218,-3.8994,2.9292,0.1330,1.9478,0.9814
98,Cc1cc(C)c(-c2c3ccccc3[n+](C)c3ccccc23)c(C)c1,-7.1381,-3.8956,2.4928,0.0000,1.9542,0.5386
99,Cc1ccc(N(c2ccc(C)cc2)c2c(C#N)c(N(c3ccc(C)cc3)c...,-5.1348,-2.1307,2.3756,0.0817,2.1533,0.2223

In [4]:
torch.manual_seed(42)
data_train, data_temp = train_test_split(df, train_size=0.9, random_state=0)
data_val, data_test = train_test_split(data_temp, train_size=0.5, random_state=0)

data_train_con = pd.concat([data_train, df_real_d])
print(data_train.shape)
print(data_train_con.shape)
data_train_con

(48837, 7)
(48937, 7)

,SMILES,eHOMO,eLUMO,DE_S0S1,f_S0S1,DE_S0T1,DES1T1
47228,Cc1cccc(C)c1B1c2ccccc2B(c2c(C)cccc2C)c2c1cccc2...,-6.021883,-2.761141,2.6090,0.0008,2.5601,0.0489
49019,C#Cc1ccc(OC)cc1OC,-5.912765,-0.808995,4.5937,0.2360,3.2077,1.3860
48317,C#CC1COCCN1c1cc(Nc2ccc(C)cc2-c2cc(C#N)c(C#N)c(...,-5.459967,-2.838693,2.1244,0.0731,1.9606,0.1638
26301,O=Cc1ccc(C(=O)c2ccc(C(=O)C(F)(F)F)cc2)cc1,-7.423270,-3.002506,3.3837,0.0021,2.7772,0.6065
23383,Cn1c(-c2c(F)c(F)c(-c3ccc(-n4c5ccccc5c5cnccc54)...,-5.926900,-1.534200,3.8233,0.8733,3.0847,0.7386
...,...,...,...,...,...,...,...
95,COc1ccc(-c2cc(-c3ccc(OC)cc3)[o+]c(-c3ccc(OC)cc...,-6.650500,-3.529900,2.6761,0.5841,2.1605,0.5156
96,C[n+]1c2ccccc2cc2ccccc21,-7.427900,-3.930700,3.0142,0.0670,1.9792,1.0350
97,C[n+]1c2ccccc2c(-c2ccccc2)c2ccccc21,-7.321800,-3.899400,2.9292,0.1330,1.9478,0.9814
98,Cc1cc(C)c(-c2c3ccccc3[n+](C)c3ccccc23)c(C)c1,-7.138100,-3.895600,2.4928,0.0000,1.9542,0.5386
99,Cc1ccc(N(c2ccc(C)cc2)c2c(C#N)c(N(c3ccc(C)cc3)c...,-5.134800,-2.130700,2.3756,0.0817,2.1533,0.2223

In [5]:
torch.manual_seed(42)

featurizer = dc.feat.MolGraphConvFeaturizer(use_edges=True)
smiles_train = data_train_con["SMILES"]
X_train = featurizer.featurize(smiles_train)
smiles_val = data_val["SMILES"]
X_val = featurizer.featurize(smiles_val)
smiles_test = data_test["SMILES"]
X_test = featurizer.featurize(smiles_test)

In [6]:
torch.manual_seed(42)

target_train_eHOMO = data_train_con["eHOMO"]
target_val_eHOMO = data_val["eHOMO"]
target_test_eHOMO = data_test["eHOMO"]

target_train_eHOMO = torch.tensor(target_train_eHOMO.values, dtype=torch.float32)
target_val_eHOMO = torch.tensor(target_val_eHOMO.values, dtype=torch.float32)
target_test_eHOMO = torch.tensor(target_test_eHOMO.values, dtype=torch.float32)

X_train_list = []
for graph_data in X_train:
    node_features = torch.tensor(graph_data.node_features, dtype=torch.float32)
    edge_index = torch.tensor(graph_data.edge_index, dtype=torch.long)
    edge_features = torch.tensor(graph_data.edge_features, dtype=torch.float32)
    data = Data(x=node_features, edge_index=edge_index, edge_attr=edge_features)
    X_train_list.append(data)
    
X_val_list = []
for graph_data in X_val:
    node_features = torch.tensor(graph_data.node_features, dtype=torch.float32)
    edge_index = torch.tensor(graph_data.edge_index, dtype=torch.long)
    edge_features = torch.tensor(graph_data.edge_features, dtype=torch.float32)
    data = Data(x=node_features, edge_index=edge_index, edge_attr=edge_features)
    X_val_list.append(data)

X_test_list = []
for graph_data in X_test:
    node_features = torch.tensor(graph_data.node_features, dtype=torch.float32)
    edge_index = torch.tensor(graph_data.edge_index, dtype=torch.long)
    edge_features = torch.tensor(graph_data.edge_features, dtype=torch.float32)
    data = Data(x=node_features, edge_index=edge_index, edge_attr=edge_features)
    X_test_list.append(data)

In [7]:
torch.manual_seed(42)

with open('data/data_train_list.pkl', 'wb') as f:
    pickle.dump(X_train_list, f)
with open('data/data_val_list.pkl', 'wb') as f:
    pickle.dump(X_val_list, f)
with open('data/data_test_list.pkl', 'wb') as f:
    pickle.dump(X_test_list, f)
with open('data/target_train_eHOMO.pkl', 'wb') as f:
    pickle.dump(target_train_eHOMO, f)
with open('data/target_val_eHOMO.pkl', 'wb') as f:
    pickle.dump(target_val_eHOMO, f)
with open('data/target_test_eHOMO.pkl', 'wb') as f:
    pickle.dump(target_test_eHOMO, f)

In [8]:
torch.manual_seed(42)

target_train_eLUMO = data_train_con["eLUMO"]
target_val_eLUMO = data_val["eLUMO"]
target_test_eLUMO = data_test["eLUMO"]

target_train_eLUMO = torch.tensor(target_train_eLUMO.values, dtype=torch.float32)
target_val_eLUMO = torch.tensor(target_val_eLUMO.values, dtype=torch.float32)
target_test_eLUMO = torch.tensor(target_test_eLUMO.values, dtype=torch.float32)

with open('data/target_train_eLUMO.pkl', 'wb') as f:
    pickle.dump(target_train_eLUMO, f)
with open('data/target_val_eLUMO.pkl', 'wb') as f:
    pickle.dump(target_val_eLUMO, f)
with open('data/target_test_eLUMO.pkl', 'wb') as f:
    pickle.dump(target_test_eLUMO, f)

In [9]:
torch.manual_seed(42)

target_train_DE_S0S1 = data_train_con["DE_S0S1"]
target_val_DE_S0S1 = data_val["DE_S0S1"]
target_test_DE_S0S1 = data_test["DE_S0S1"]

target_train_DE_S0S1 = torch.tensor(target_train_DE_S0S1.values, dtype=torch.float32)
target_val_DE_S0S1 = torch.tensor(target_val_DE_S0S1.values, dtype=torch.float32)
target_test_DE_S0S1 = torch.tensor(target_test_DE_S0S1.values, dtype=torch.float32)

with open('data/target_train_DE_S0S1.pkl', 'wb') as f:
    pickle.dump(target_train_DE_S0S1, f)
with open('data/target_val_DE_S0S1.pkl', 'wb') as f:
    pickle.dump(target_val_DE_S0S1, f)
with open('data/target_test_DE_S0S1.pkl', 'wb') as f:
    pickle.dump(target_test_DE_S0S1, f)

In [10]:
torch.manual_seed(42)

target_train_f_S0S1 = data_train_con["f_S0S1"]
target_val_f_S0S1 = data_val["f_S0S1"]
target_test_f_S0S1 = data_test["f_S0S1"]

target_train_f_S0S1 = torch.tensor(target_train_f_S0S1.values, dtype=torch.float32)
target_val_f_S0S1 = torch.tensor(target_val_f_S0S1.values, dtype=torch.float32)
target_test_f_S0S1 = torch.tensor(target_test_f_S0S1.values, dtype=torch.float32)

with open('data/target_train_f_S0S1.pkl', 'wb') as f:
    pickle.dump(target_train_f_S0S1, f)
with open('data/target_val_f_S0S1.pkl', 'wb') as f:
    pickle.dump(target_val_f_S0S1, f)
with open('data/target_test_f_S0S1.pkl', 'wb') as f:
    pickle.dump(target_test_f_S0S1, f)

In [11]:
torch.manual_seed(42)

target_train_DE_S0T1 = data_train_con["DE_S0T1"]
target_val_DE_S0T1 = data_val["DE_S0T1"]
target_test_DE_S0T1 = data_test["DE_S0T1"]

target_train_DE_S0T1 = torch.tensor(target_train_DE_S0T1.values, dtype=torch.float32)
target_val_DE_S0T1 = torch.tensor(target_val_DE_S0T1.values, dtype=torch.float32)
target_test_DE_S0T1 = torch.tensor(target_test_DE_S0T1.values, dtype=torch.float32)

with open('data/target_train_DE_S0T1.pkl', 'wb') as f:
    pickle.dump(target_train_DE_S0T1, f)
with open('data/target_val_DE_S0T1.pkl', 'wb') as f:
    pickle.dump(target_val_DE_S0T1, f)
with open('data/target_test_DE_S0T1.pkl', 'wb') as f:
    pickle.dump(target_test_DE_S0T1, f)

In [12]:
torch.manual_seed(42)

y_DES1T1 = df["DES1T1"]
target_train_DES1T1 = data_train_con["DES1T1"]
target_val_DES1T1 = data_val["DES1T1"]
target_test_DES1T1 = data_test["DES1T1"]

target_train_DES1T1 = torch.tensor(target_train_DES1T1.values, dtype=torch.float32)
target_val_DES1T1 = torch.tensor(target_val_DES1T1.values, dtype=torch.float32)
target_test_DES1T1 = torch.tensor(target_test_DES1T1.values, dtype=torch.float32)

with open('data/target_train_DES1T1.pkl', 'wb') as f:
    pickle.dump(target_train_DES1T1, f)
with open('data/target_val_DES1T1.pkl', 'wb') as f:
    pickle.dump(target_val_DES1T1, f)
with open('data/target_test_DES1T1.pkl', 'wb') as f:
    pickle.dump(target_test_DES1T1, f)